CREATE USER Konyvtaros IDENTIFIED BY 12345678;

GRANT CREATE ANY TRIGGER TO Konyvtaros;
GRANT CREATE TABLE TO Konyvtaros;
GRANT UNLIMITED TABLESPACE TO Konyvtaros;
GRANT CREATE SEQUENCE TO Konyvtaros;
GRANT CREATE VIEW TO Konyvtaros;
GRANT CREATE TYPE TO Konyvtaros;
GRANT CREATE ANY PROCEDURE TO Konyvtaros;
GRANT CREATE SESSION TO Konyvtaros;
